### PR TITLE
Fix issue with simultaneous query execution for the same connection

### PR DESCRIPTION
**Pull request by OlegDokuka**
The following PR fix issue when we execute several Queries to the same connection.

### CODE REVIEW

**Comment by nebhale** [comment]
@OlegDokuka I'm not sure why this would need to be solved.  PostgreSQL doesn't allow multiplexing on connections and pipelining isn't dependable or desirable.  We'd planned on honoring the same semantics the database expects that there is only a single "user" of a connection at a given time.  This would imply that you wouldn't have "simultaneous" queries on a single connection.

**Comment by OlegDokuka** [comment]
Hey @nebhale.

Take a look at the code. Either it is supported or not, one can write simultaneous execution and we do not have protection from that. Recently I did a demo for the presentation of r2dbc, and will not be able to run simple case during the transaction.
Since transaction uses the same connection, it is really easy to subscribe twice to the same source, since responseEmitter.next() does not guarantee that each new subscriber receives different element.

Thus, this PR makes sense, until there is another protection will be introduced

**Comment by OlegDokuka** [comment]
It is possible that I misunderstood you, do you mean provide protection on the higher level?

**Comment by nebhale** [comment]
Well, no protection per se, just an understanding that like JDBC or the database drivers in other languages, only a single query can be executed at a given time.  In a pooling scenario, you'd take a connection from a pool, execute your query and get your results and then return the connection to the pool for the next person to use it.

**Comment by nebhale** [comment]
@OlegDokuka Not sure what you mean that for non-transaction it does not work.  If you follow a transaction to its completion (commit or rollback), you can safely hand back the connection for further usage.

**Comment by OlegDokuka** [comment]
The problem is the following. You have a database client. Then you start a transaction and receive a connection. Then you execute two queries using zip. In the client, those queries will be sent to the same `ReactorNettyClient` over `#exchange` with the same connection. Both will be enqueued in the `requestEmitter` processor and then both will be subscribed to responseEmitter using `next` method. Both will receive the same UnicastWindowFluxInner and some of the will get an error. This is the problem.

**Comment by nebhale** [comment]
Ah, yeah the use of `zip()`.  That makes sense.

**Comment by mp911de** [comment]
I assume this fix is widely applicable for R2DBC drivers that use networking without an async-ready protocol.

**Comment by nebhale** [comment]
Multiplexed protocol would be the key I think.  The ability to have more than one simultaneous query over a single socket connection.

**Pull request closed without merging**
