### PR TITLE
[131] Replace RuleBasedCollector with simple ignore case string matcher

### PR DESCRIPTION
**Pull request by Aleksandr-Filichkin**
Replace RuleBasedCollector with ignoring case string matcher, because RuleBasedCollector has synchronized compare method

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Aleksandr-Filichkin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=132)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=132) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Aleksandr-Filichkin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=132)!

**Comment by Aleksandr-Filichkin** [comment]
@nebhale , @mp911de Maven build is failde due to 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project r2dbc-postgresql: Compilation failure
[ERROR] /tmp/build/80754af9/r2dbc-postgresql/src/main/java/io/r2dbc/postgresql/PostgresqlConnection.java:[41,14] io.r2dbc.postgresql.PostgresqlConnection is not abstract and does not override abstract method validate(io.r2dbc.spi.ValidationDepth) in io.r2dbc.spi.Connection

**Comment by odrotbohm** [comment]
I just pinged @nebhale about the necessary updates in the SPI compatibility.

**Comment by mp911de** [comment]
Thanks a lot for your contribution. That's merged now.

**Pull request closed without merging**
