### PR TITLE
Simplify factory provider

### PR DESCRIPTION
**Pull request by ask4gilles**
proposal to simplify the ```PostgresqlConnectionFactoryProvider```

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks for your pull request. Moving the initialization into the `Builder` is an interesting option that would allow applications to pre-initialize the builder with `ConnectionFactoryOptions`. We probably should inline parts of the methods (such as not having an individual method per SSL option).

It would also make sense to expose `builder(ConnectionFactoryOptions)` statically to obtain an initialized builder instead of a method that applies `ConnectionFactoryOptions` to an existing builder. Applying some other configuration object bears always the risk that previously configured options get overwritten and by returning a pre-initialized builder, we're able to avoid this risk.

**Comment by ask4gilles** [comment]
Hi Mark,
I've pushed some modifications according to your remarks.

**Comment by mp911de** [comment]
Thanks a lot. While reviewing the code I realized that moving the initialization `ConnectionFactoryOptions`-based initialization to `PostgresqlConnectionConfiguration.Builder` causes a cycle between `PostgresqlConnectionConfiguration.Builder` and `PostgresqlConnectionFactoryProvider` as driver-specific options are declared in `PostgresqlConnectionFactoryProvider`.

I'm going to move the entire `fromConnectionFactoryOptions(…)` method tree back to `PostgresqlConnectionFactoryProvider` preserving the optimizations from the original pull request.

**Comment by mp911de** [comment]
That's merged and polished now.

**Comment by ask4gilles** [comment]
Thanks Mark!

**Pull request merged**
