### PR TITLE
SCRAM authentication

### PR DESCRIPTION
**Pull request by Squiry**
I've tried to implement SASL Authentication authentication here (#6), but I have a few questions.

1. @davecramer mentioned client implementation library and I used it. I don't know is it ok though.
2. That library throws a couple of checked exceptions (like can't parse, invalid signature, etc) and I'm not quite sure how to wrap them.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Squiry Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=63)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=63) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Squiry Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=63)!

**Comment by nebhale** [comment]
Thanks for the contribution.  I'm reviewing now.  For next time, just drop a line in the main issue (in this case #6) to let everyone know not to work on it 😄

**Comment by Squiry** [comment]
I was planning only to take a look on what to do and accidentally wrote some code. So, yeah! Next time I'll drop a line for sure!

**Comment by nebhale** [comment]
@davecramer What's the easiest way, given an installed PostgreSQL to test SCRAM authentication?  Can I change a single file and magically something works?

**Comment by Squiry** [comment]
@nebhale I've left test case for SCRAM auth in ReactorNettyClientTest with test containers. So I belive you can just repeat it with an installed database as well.

**Pull request closed without merging**
