### PR TITLE
High availability cluster merge

### PR DESCRIPTION
**Pull request by vtk**
Merged conflicts for feature high-availability-cluster  that was implemented by @Squiry with latest master

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@vtk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=250)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=250) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@vtk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=250)!

**Comment by mp911de** [comment]
Thanks for your effort. Creating a PR on top of another PR brings us in a weird situation as the previous PR had several comments attached and it wasn't abandoned.

**Comment by vtk** [comment]
> Thanks for your effort. Creating a PR on top of another PR brings us in a weird situation as the previous PR had several comments attached and it wasn't abandoned.

No problem i can try to fix those comments

**Comment by mp911de** [comment]
@Squiry what's your opinion on this PR?

**Comment by Squiry** [comment]
My plan was to rewrite it from scratch since we need some more flexible mechanism of server-picking, so I'm not sure that there's any point in conflict resolving. But if we're going to keep interface as it is right now then we can continue in this PR.

**Comment by mp911de** [comment]
I'm also in favor of closing this PR. If you plan to rewrite yours, then probably it makes also sense to close #203 and start with a fresh PR.

**Comment by mp911de** [comment]
Closing this PR without a merge as per the previous comment.

**Pull request closed without merging**
