### PR TITLE
Fix canDecode for arrays

### LINKED ISSUE #113: Array codecs missing during `canDecode(..)` implementation
I'm trying to get a column of type `TEXT[]` in PostgreSQL so I'm mapping it in my entity as `String[]`. Everything worked as expected until I added the `String[]` filed to my entity and database, after that I got the following error:
```
Caused by: java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object
	at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:96) ~[r2dbc-postgresql-1.0.0.M7.jar:na]
	at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:83) ~[r2dbc-postgresql-1.0.0.M7.jar:na]
	at io.r2dbc.spi.Row.get(Row.java:46) ~[r2dbc-spi-1.0.0.M7.jar:na]
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter$RowParameterValueProvider.getParameterValue(MappingR2dbcConverter.java:426) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	... 81 common frames omitted
```

I noticed the error said the data type was `java.lang.Object`, but it seems this comes from `org.springframework.data.r2dbc` using the default `get(..)` method from the `Row` interface. However, I debugged a bit around the [canDecode(..)](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/AbstractCodec.java#L38) implementation in [AbstractCodec.java](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/AbstractCodec.java) (in [this](https://github.com/r2dbc/r2dbc-postgresql/blob/f8a358141089de9e47f4e73f672e2db7f6df1f3c/src/main/java/io/r2dbc/postgresql/codec/AbstractCodec.java#L43) line to be precise), and I notices the following codecs are not being tested (from [DefaultCodecs.java](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/DefaultCodecs.java)):
```java
new ShortArrayCodec(byteBufAllocator),
new StringArrayCodec(byteBufAllocator),
new IntegerArrayCodec(byteBufAllocator),
new LongArrayCodec(byteBufAllocator)
```

I'm not really sure why they are not being tested, but I hope this information helps to find the source of the issue.

Hope a fix can be merged and released soon. Also, thanks in advance 🙂

### PR DESCRIPTION
**Pull request by JoseLion**
@nebhale this one fixes #113 , please let me know what you think 🙂

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@JoseLion Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=115)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=115) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@JoseLion Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-postgresql&pullRequestId=115)!

**Comment by JoseLion** [comment]
Hi @nebhale, any update on this PR?

**Comment by Aleksandr-Filichkin** [comment]
Any updates on this? We see the same problem

**Comment by gregturn** [comment]
Resolved via https://github.com/r2dbc/r2dbc-postgresql/commit/be890c165619e19b68e2b4ec293063bc10be96b9.

**Pull request closed without merging**
